stages:
  - build

build-trayapp:
  stage: build
  tags:
    - windows
  script:
    - echo "Building TrayApp Windows Service"
    - cmake -B out/build/x64-release -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release
    - cmake --build out/build/x64-release --config Release
    - dir out\build\x64-release\bin\Release\*.exe
  artifacts:
    paths:
      - out/build/x64-release/bin/Release/TrayService.exe
      - out/build/x64-release/bin/Release/TrayApp.exe
    expire_in: 30 days